### ISSUE TITLE
Add Download Option

### ISSUE THREAD

**Issue by liberodark** [Atraci/Atraci#231]
Hello,

Add an option to download movie or converte in mp3 please.
kind regards

**Comment by OneMoreThing** [comment]
Please add as an optional feature or external plugin to add download (mp3/mp4). As example to handle the download you can see this project https://github.com/shubapp/u2bear

**Comment by Draxler** [comment]
@OneMoreThing 
u2bear is realy nice app, simillar in some ways with Atraci. On the other hand, these 2 apps are defferent in a big way.  That's why Atraci couldn't use downloading option as they do, among other things..  Why is that, it was already explained in previous comments ...
Regards
