### ISSUE TITLE
Video View

### ISSUE THREAD

**Issue by miriampl** [Atraci/Atraci#250]
Hi there 
First of all very nice and useful app :D 

I have suggestion

Please make a button script to turn on / off video. 
Button TURN ON:
![zrzut ekranu z 2015-01-03 00 33 06](https://cloud.githubusercontent.com/assets/2357683/5600715/ccc345b2-92e0-11e4-9ba2-077da959692e.png)
Button TURN OFF:
![zrzut ekranu z 2015-01-03 00 33 31](https://cloud.githubusercontent.com/assets/2357683/5600719/cf9c7d76-92e0-11e4-9654-086878425125.png)

I have run the developer tools and turn off HTML CODE: 

It still working but no video form site. 

If i'm getting this app right you just change the display from youtube video so even if i deleted this video view i still getting the full video download to my computer. Do you work on any conversion from video to mp3 or something like this? I think that would make the bandwidth consumption less expensive :D

**Comment by avihaymenahem** [comment]
Yes, it makes the bandwidth less expensive but youtube currently doesnt allow that from their API.
Video must be shown.
