### ISSUE TITLE
RPM Builds for Fedora 21 -- (how do i submit them?)

### ISSUE THREAD

**Issue by fa7ad** [Atraci/Atraci#253]
Hey guys, 

I converted the Linux x64 zip to proper Fedora 21 amd64 RPM (With Icons and everything added)

How do I pass them on to you guys (say, for later releases), so that you can test/post them ?

P.S. 
I think I used version 0.7.0
Here are the the files on my gDrive: http://hope.ly/1CbjVQ1

**Comment by 5punk** [comment]
Hey Thank you so much for that. Could you please have a word with Andy from webupd8.org?

**Comment by fa7ad** [comment]
Sure, why not 😀

**Comment by fa7ad** [comment]
Hey, don't use these RPMs yet. I did not realize this but, rpmbuild automatically added a bad dependency `libudev.so.0()`
I'll see what I can do to possibly fix and re-compile :smile:
