### ISSUE TITLE
Can't build Atraci

### ISSUE THREAD

**Issue by mimi89999** [Atraci/Atraci#257]
Console log:
Building 0.7.0

Running "compass:dist" (compass) task

Running "coffeelint:app" (coffeelint) task
>> 20 files lint free.

Running "coffee:compileBare" (coffee) task
>> 1 files created.

Running "uglify:target" (uglify) task

Running "cssmin:minify" (cssmin) task
File css/app.css created: 16.62 kB → 16.62 kB

Running "clean:0" (clean) task
>> 0 paths cleaned.

Running "regex-replace:windows_installer" (regex-replace) task
File 'dist/win/windows-installer.iss' replace complete.

Running "nodewebkit:src" (nodewebkit) task
Using v0.10.1
Create cache folder in /home/michel/Téléchargements/Atraci-master/cache/0.10.1
Downloading: http://dl.node-webkit.org/v0.10.1/node-webkit-v0.10.1-linux-x64.tar.gz
undefined
Fatal error: Unable to download nodewebkit.

**Comment by shyne99** [comment]
It come from a change in the uri of download of nodewebkit. It's not http://dl.node-webkit.org/ anymore, it change to http://dl.nwjs.io/.

**Comment by fa7ad** [comment]
Thanks for the simple fix in #259. Added it on my fork, I downloaded nw manually last time I compiled. This is awesome :+1:
