### ISSUE TITLE
Oops, something went wrong...

### ISSUE THREAD

**Issue by hotrush** [Atraci/Atraci#273]
Trying to install atraci two times - about a month ago and now. But unfortunaly it is still not working.
```
Linux Mint 17.1 x64
3.13.0-37-generic
```
http://pastebin.com/En9TgEEp

**Comment by fa7ad** [comment]
Atraci has been abandoned. try [Kaku](http://kaku.rocks)

**Comment by hotrush** [comment]
will try, thanks
