### ISSUE TITLE
Build/Run issue on Fedora 23

### ISSUE THREAD

**Issue by gbggit** [Atraci/Atraci#276]
I'm not sure if this is Atraci's problem or Fedora's one, but there is an issue with the symlink of libudev.so.0. To get it work, I've to add it manually: 

`sudo ln -s /lib64/libudev.so.1.6.4 /lib64/libudev.so.0`

**Comment by fa7ad** [comment]
Atraci is abandoned. Please find something else. 
I personally like [kaku](http://kaku.rocks), the guy who made it used to contribute here too

**Comment by gbggit** [comment]
@fa7ad thanks, will give kaku a try.
