### ISSUE TITLE
Minimize to systray

### ISSUE THREAD

**Issue by LanderMalta** [Atraci/Atraci#88]
Atraci could have one more option to be minimized to the systray, and gain more space for other tasks while the use

**Comment by Israphel** [comment]
In linux you can use alltray
![sese](https://cloud.githubusercontent.com/assets/720191/5808125/d937ebec-a008-11e4-8570-abad872c7fa5.png)

**Comment by avihaymenahem** [comment]
Can you add this as a feature request in here?
https://github.com/Atraci/Atraci-Angular

**Comment by LanderMalta** [comment]
yes of course
