### ISSUE TITLE
Failed compile in Fedora 21

### ISSUE THREAD

**Issue by kuboosoft** [Atraci/Atraci#95]
Hi, please update to current version of sass.
Log:
[33mWarning: Command failed: /usr/share/rubygems/rubygems/dependency.rb:298:in `to_specs': Could not find 'sass' (~> 3.2.17) - did find: [sass-3.3.8] (Gem::LoadError)
    from /usr/share/rubygems/rubygems/specification.rb:1295:in`block in activate_dependencies'
    from /usr/share/rubygems/rubygems/specification.rb:1284:in `each'
    from /usr/share/rubygems/rubygems/specification.rb:1284:in`activate_dependencies'
    from /usr/share/rubygems/rubygems/specification.rb:1266:in `activate'
    from /usr/share/rubygems/rubygems/core_ext/kernel_gem.rb:54:in`gem'
    from /usr/bin/compass:22:in `<main>'

**Comment by pauliuszaleckas** [comment]
compass requires older sass verion.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1152676
